### ISSUE TITLE
Rails 4 -> 5 behavior of .never.with() changes

### ISSUE THREAD

**Issue by srvance** [freerange/mocha#484] opened 2020-07-21 13:22 UTC
I've run into the behavior noted in #82, but strangely, the test passes under Rails 4 but fails as described under Rails 5. I haven't been able to track down any reasons for the difference. I see this under mocha 1.1.0 and 1.11.2.

Specifically,

```
Rails.logger.expects(:info).never.with('foo')
```
is the code in question. I can work around it in both versions by adding the following, which is consistent with the explanation in the other issue.
```
Rails.logger.expects(:info).with(Not equals 'foo')
```
Any ideas on the difference in behavior?

Also, I see that while the issue has a bunch of good examples and explanation, that never made it into the documentation. While there may not be any universally intuitive behavior, the documentation is incomplete and allows any interpretation. Can the examples and explanations from the other issue get folded into the docs?

**Comment by floehopper** [comment] 2020-07-21 20:07
@srvance 

Thanks for reporting the issue and for taking the time to find the old related issue.

> Any ideas on the difference in behavior?

Do you mean why are you seeing different behaviour between Rails v4 and Rails v5? If so, then no, I don't have any ideas off the top of my head. Is the version of Rails definitely the *only* thing that's changing between the two scenarios? Do you know what test framework you are using and what versions in each scenario?

Can you paste a full example test and implementation demonstrating the issue, so I can reproduce the behaviour locally. If you can give me that then I'd be happy to investigate what's going on with the different versions of Rails.

> Also, I see that while the issue has a bunch of good examples and explanation, that never made it into the documentation. While there may not be any universally intuitive behavior, the documentation is incomplete and allows any interpretation. Can the examples and explanations from the other issue get folded into the docs?

That's a good idea. I've added #485 to remind us to do something about that. Were there any examples/explanations in #82 that you found particularly helpful?

**Comment by srvance** [comment] 2020-07-21 21:46
The only difference is Rails 4 vs 5 and some required associated gem versions. We've been conservative in gem version updates.

I can see if I can reconstruct it, but the context is fairly embedded in an old and large app. Copying it would be prohibitive and probably not allowed.

Thanks for the issue on that. I think the enumeration of the various permutations around never were really good. The issue that is surprising but not obvious from the current docs is the behavior of `.never.with('foo')` when it's called with `'bar'`, so the matching and different cases there would illuminate that well.

**Comment by floehopper** [comment] 2020-07-22 16:58
> The only difference is Rails 4 vs 5 and some required associated gem versions. We've been conservative in gem version updates.
> 
> I can see if I can reconstruct it, but the context is fairly embedded in an old and large app. Copying it would be prohibitive and probably not allowed.

OK. In these situations, I usually create a new vanilla Rails app and just try to re-create a representative example to demonstrate the problem, pushing the code up into a repo on GitHub. Unless it's something really obvious (which it doesn't appear to be in this case), without being able to reproduce the problem locally, it's really impossible for me to investigate further.

Can I just confirm that you're just seeing different behaviour in the Rails v4 vs Rails v5 scenarios I wanted to check you're not seeing some kind of unexpected exception in either case, because if you are, I might be able to investigate that if you gave me the stack trace.

> Thanks for the issue on that. I think the enumeration of the various permutations around never were really good. The issue that is surprising but not obvious from the current docs is the behavior of `.never.with('foo')` when it's called with `'bar'`, so the matching and different cases there would illuminate that well.

That's helpful, thank you. I've updated #485 accordingly.

I'm going to close this issue for now, but feel free to re-open it if you can supply code to reproduce the problem or a stack trace from an unexpected exception.

**Closed by floehopper** 2020-07-22 16:58 UTC
Labels: under-investigation
