### ISSUE TITLE
Optional hash parameters are now required in `.expects.with`

### ISSUE THREAD

**Issue by myprivatealaska** [freerange/mocha#670] opened 2024-07-29 18:21 UTC
We have noticed new behavior in `.expects.with` in the `v2.4.0` update. Essentially, all optional hash parameters are now required in `.expects`. 

Example
```
# A method on the Producer with an optional Hash parameter
def self.produce_sync(channel:, event:, options: {})

# This used to work prior to the `v2.4.0` update
Producer
                  .expects(:produce_sync)
                  .with(
                    channel: channel,
                    event: event_mock,
                  )
                  .once

# Have to explicitly pass in the optional parameter now after the `v2.4.0` update for the matcher to work
Producer
                  .expects(:produce_sync)
                  .with(
                    channel: channel,
                    event: event_mock,
                    options: {},
                  )
                  .once
```

I suspect this new behavior was introduced by [this commit](https://github.com/freerange/mocha/commit/5e6a07b2710dac76e9346def561ca0d44765bf86). Is this change intentional or a regression?

**Comment by floehopper** [comment] 2024-07-30 08:26
I believe this is effectively a duplicate of #667.

A regression was accidentally introduced in v2.3.0 and only fixed in v2.4.3, so I'm guessing that your test was written in the period between these two releases.

If you don't care about some keyword arguments, then you can use a matcher like [`Mocha::ParameterMatchers#has_entries`](https://mocha.jamesmead.org/Mocha/ParameterMatchers.html#has_entries-instance_method). So you example would become:

```ruby
def self.produce_sync(channel:, event:, options: {})

Producer.expects(:produce_sync).with(has_entries(channel: channel, event: event_mock)).once
```

I'm going to close this as a duplicate, but please let me know if I've misunderstood something.

**Closed by floehopper** 2024-07-30 08:26 UTC
