### ISSUE TITLE
allow yielding with the parameters passed to the method

### ISSUE THREAD

**Issue by akostadinov** [freerange/mocha#291] opened 2016-12-16 22:56 UTC
I would like to do something like this:
```ruby
XUnitImporter.any_instance.expects(:send_run).yields { |*params|
  # now I can check what params have been passed
  # return of block is used as a return from the mehtod.
}
```
This is when one doesn't exactly know what params will be sent to method. e.g. using a sample from example data instead of hardcoded values.

**Comment by floehopper** [comment] 2016-12-17 10:52
@akostadinov: I hope you don't mind, but I've switched on Ruby syntax highlighting for your code block to make things clearer.

**Comment by floehopper** [comment] 2016-12-17 10:52
@akostadinov: I don't understand what you are trying to test. Please can you post an actual example (i.e. not pseudo-code/comments) and include the full code for both the test _and_ the method under test? Also please explain under what conditions you expect the test to fail.

**Comment by akostadinov** [comment] 2016-12-17 14:50
Thanks for ruby syntax. I don't have a ready test case because I couldn't figure out how to write it. But I'll prepare something that I'd like to work next week and get back to you.

**Comment by floehopper** [comment] 2016-12-17 16:07
@akostadinov: OK. In that case, I'm going to close this issue for now. Please re-open it when you have a complete code example to demonstrate what you want to achieve.

**Comment by akostadinov** [comment] 2016-12-21 16:21
@floehopper , I don't think I have permissions to reopen issues in this project. Perhaps you need to reopen it.

In any case, below is code that you requested. I didn't include the methods under test because it is only processing request params and generating some XML based on database content, that is in turn passed to the importer. I just wanted to mock the importer as it is interacting with an external service so is better tested separately. But if you think it would help, I can paste more code.

I figured how to achieve what I want in this particular test. Here's a little simplified but working code:
```
  test "should push existing test run" do
    fake_importer = Object.new
    def fake_importer.send_run(xunit_str)
      verify_xunit_str xunit_str # here is what I want to do
      {success: true}
    end

    CucuShift::XUnitImporter.expects(:instance).once.returns(fake_importer)
    begin
      put(
        push_test_run_url(run_id: "auto-test-run-poc-ik5f1", project_id: "OSE")
      )
      assert_response :accepted
      mocha_verify
    ensure
      CucuShift::XUnitImporter.unstub(:instance)
    end
  end
```

Now I create and manage to inject a fake importer at the right place. I call `verify_xunit_str` method over the parameter passed to `send_run`. `verify_xunit_str` would raise if parameter is malformed or unexpected which in turn will mess up the response thus test will fail.

It is often not easy to inject your own object. I would like to be able to do something like:
```
  test "should push existing test run" do
    CucuShift::XUnitImporter.any_instance.expects(:send_run).once.with_actual_params do |xunit_str|
      verify_xunit_str xunit_str # here is what I want to do
      {success: true}
    end
    begin
      put(
        push_test_run_url(run_id: "auto-test-run-poc-ik5f1", project_id: "OSE")
      )
      assert_response :accepted
      mocha_verify
    ensure
      CucuShift::XUnitImporter.any_instance.unstub(:send_run)
    end
  end
```
The point here is `expects(:send_run).once.with_actual_params`. This would mock the `#send_run` method so that it actually executes the block with the parameters as used by the caller. The return value of the block will be used as a return value from the method call. This would open a lot of possibilities to validate parameters passed to the method as well returning different values depending on the parameters passed.

**Comment by floehopper** [comment] 2016-12-21 16:41
> I don't think I have permissions to reopen issues in this project. Perhaps you need to reopen it.

Done.

**Comment by floehopper** [comment] 2017-01-03 13:39
@akostadinov: Sorry we've been away over the Christmas period. We'll get back to you as soon as we can.

**Comment by floehopper** [comment] 2017-01-11 14:21
@akostadinov:

I'm sorry for the slow reply.

I'm still a bit confused about what you're trying to do. In particular, your original question talked about passing a block to [Mocha::Expectation#yields](http://gofreerange.com/mocha/docs/Mocha/Expectation.html#yields-instance_method), whereas your most recent comment talks about introducing a new `with_actual_params` method which sounds more like [Mocha::Expectation#with](http://gofreerange.com/mocha/docs/Mocha/Expectation.html#with-instance_method). Which of these do you mean?

Assuming your more recent comment best describes what you're trying to do, [Mocha::Expectation#with](http://gofreerange.com/mocha/docs/Mocha/Expectation.html#with-instance_method) already allows you to pass an arbitrary block which is used to determine whether the parameters passed to the stubbed method are as expected.

This mechanism is intended to allow you to implement custom parameter matchers if none of the [built-in matchers](http://gofreerange.com/mocha/docs/Mocha/ParameterMatchers.html) will do what you want. Here's an example where I've done this:

Test implementation: https://github.com/freerange/goos-ruby/blob/3903e452d73bee0c3522d03f6673ef47c6123dbe/test/unit/auction_sniper_test.rb#L22
Matcher implementation: https://github.com/freerange/goos-ruby/blob/3903e452d73bee0c3522d03f6673ef47c6123dbe/test/unit/auction_sniper_test.rb#L179-L181

Note that this mechanism does _not_ allow you to return different values depending on what parameters are passed in; the block is only used to determine whether the relevant stub matches the parameters. The way to have the stubbed method return different values depending on the parameters is to setup multiple stubs for the same method:

```ruby
class FooTest < Minitest::Test
  def test_bar
    foo = mock('foo')
    foo.stubs(:bar).with(&a_small_number).returns(:small)
    foo.stubs(:bar).with(&a_big_number).returns(:big)
    assert_equal :small, foo.bar(99)
    assert_equal :big, foo.bar(100)
  end

  private

  def a_small_number
    -> (value) { value < 100 }
  end

  def a_big_number
    -> (value) { value >= 100 }
  end
end
```

For me one of the points of a [Mock Object](http://xunitpatterns.com/Mock%20Object.html) is to explicitly define the return values within the test so it's easy to understand what's going on. What you are talking about sounds more like a [Fake Object](http://xunitpatterns.com/Fake%20Object.html). Although Mocha can be used to build simple Fake Objects, it's not what it was designed for and we don't have any plans to change that.

I hope that some of what I've written is helpful. I'm going to close this issue for now, but please let me know if you have more questions and/or you want to re-open it.

**Closed by floehopper** 2017-01-11 14:21 UTC
Labels: under-investigation
