### ISSUE TITLE
Unable to use instance_of parameter matcher

### ISSUE THREAD

**Issue by Bennet-Sunder** [freerange/mocha#482] opened 2020-03-29 02:30 UTC
I want to use a `instance_of` parameter matcher for a test in `ActionController::TestCase`. I have imported the following files 
`require 'mocha/api'`
`require 'mocha/setup'`

 I wish to write something like this. 
`Book.any_instance.stubs(:read).with(instance_of(String)).returns true`

But I get a message no method error for `instance_of`. Although I am able to use it in another file where it is configured for RSpec. 
Could you please let me know the required files I need to import to use the parameter matchers

**Comment by floehopper** [comment] 2020-03-29 11:16
@Bennet-Sunder 

I'm a bit confused whether you're using MiniTest or RSpec. The fact you talk about an `ActionController::TestCase` suggests that you're using the built-in testing functionality in a Rails app. Is that correct? 

If so, you should follow [these instructions for Rails/Minitest][1], i.e. `require 'mocha/minitest'` at the bottom of `test_helper.rb` or at least after the `require 'rails/test_help'` statement.

Out of interest, what prompted you to require 'mocha/api' and 'mocha/setup'? I'm wondering whether the documentation can be improved.

[1]: https://mocha.jamesmead.org/index.html#Rails

**Comment by Bennet-Sunder** [comment] 2020-03-29 14:17
@floehopper 

So the RSpec is configured as per the instruction and i'm able to use all the parameter matchers. 
For the controller minitests I use `gem "minitest-rails", "2.1.1"` and `gem "mocha", "~> 0.13.0", require: false`
and in the `test_helper.rb` 
```
require 'minitest/rails'
require 'mocha/setup'
```
Here is where I tried to add `require 'mocha/api'` in hope of using the parameter matcher but didn't work. 
I did try to add `require 'mocha/minitest'` and for some reason, it gave me a load error. 

I hope it clarifies what I'm trying to do.

**Comment by floehopper** [comment] 2020-03-29 15:51
What the exact version of the mocha gem you are using. You can find this in `Gemfile.lock`.

What version of rails are you using? That looks like a very old version of minitest-rails.

What version of Ruby are you using?

Is there a particular reason you're useing **both** minitest **and** rspec? e.g. could you not use [rspec controller specs][1]?

[1]: https://relishapp.com/rspec/rspec-rails/docs/controller-specs

**Comment by Bennet-Sunder** [comment] 2020-03-30 03:10
```
Rails => 4.2.1
Ruby => 2.4.7
minitest-rails => 2.1.1
```
mocha has two entries in the `gemfile.lock` section one of them is `mocha (0.13.3)` under the `spec` section and `mocha (~> 0.13.0)` under the `dependencies` section.
I'm working with existing tests which were written with 'minitest/rails' so can't change them now.

**Comment by floehopper** [comment] 2020-03-30 10:33
OK. The `mocha (0.13.3)` is the version that bundler has actually installed. I'll see whether I can reproduce your environment locally.

**Comment by floehopper** [comment] 2020-03-30 11:28
I'm having trouble trying to reproduce this (apparently pretty old) environment. Please can you post your full `Gemfile` and `Gemfile.lock` to help me?

**Comment by Bennet-Sunder** [comment] 2020-03-30 12:49
@floehopper 

Unfortunately, I cannot post that since it's a private repo.

**Comment by floehopper** [comment] 2020-03-30 15:09
> Unfortunately, I cannot post that since it's a private repo.

Hmm. I can't even get a simple controller test to run in a project with that version of Ruby & Rails, so I'm going to struggle to help you without more information.

If you want definitive help from me on this, please can you create a new vanilla Rails app (using `rails new`) with the same versions of relevant gems as your private project and add a simple test to demonstrate the problem you are having. Then share this project in a public repo on GitHub (or similar).

Otherwise you could try including `Mocha::API` into a relevant test case to see whether that gives you what you want. I'm hesitant to suggest this, because I don't have a lot of confidence that it's the correct solution and if it's not, it might lead to other weirdness in your test suite. i.e. this approach comes with no guarantee from me!

**Comment by Bennet-Sunder** [comment] 2020-04-01 05:34
including `Mocha::API` indeed did work. That fixes things for me now since I need it only one file.

However, I'll try and reproduce in a separate project and get back to you. Thanks!

**Comment by floehopper** [comment] 2020-04-01 10:29
OK. That's good. I'm going to close this issue for now, but please do re-open it if you manage to reproduce the problem in a new Rails project.

**Closed by floehopper** 2020-04-01 10:29 UTC
Labels: under-investigation
