### ISSUE TITLE
Stubbing class methods defined by extending a module is broken in 1.8.x

### ISSUE THREAD

**Issue by chrisroos** [freerange/mocha#259] opened 2016-08-25 14:52 UTC
You can see the broken behaviour by removing the `unless Mocha::PRE_RUBY_V19` condition from around the `StubMethodDefinedOnModuleAndAliasedTest` test and running it using Ruby 1.8.7.

This is related to PR #244. The problem described in PR #244 should be fixed in Ruby 1.9 and above but remains broken in 1.8.x.

**Comment by floehopper** [comment] 2022-08-15 19:50
Although #244 and associated issues (#260, #262) suggest that this might be fixed in Ruby v1.8.7, removing the guard condition from `StubMethodDefinedOnModuleAndAliasedTest` still results in an exception in [the Ruby v1.8 build](https://app.circleci.com/pipelines/github/freerange/mocha/124/workflows/72598b41-17ce-451a-b279-bce9ceb05d33/jobs/1738). However, since the problem is quite an obscure one which relates to a very old version of Ruby, I'm unlikely to fix it any time soon unless someone submits a patch. So I'm going to close this issue.

**Closed by floehopper** 2022-08-15 19:50 UTC
Labels: bug-report
