### ISSUE TITLE
Detecting stubbing outside of tests

### ISSUE THREAD

**Issue by lzap** [freerange/mocha#326] opened 2018-03-27 13:02 UTC
Hello,

on our huge codebase (https://github.com/theforeman/foreman) we have couple of places where we stub few things outside of a test case (global context or test class-level context) and it is causing troubles. I was wondering if there is a mechanism in mocha to detect such a situation (or even better - to prevent it optionally).

Here is an example what we do:

```ruby
require "mocha"
require "singleton"
require 'test/unit'
require 'mocha/test_unit'

class ASingleton
  include Singleton

  def test
    "real"
  end
end

module AStubber
  def self.included(base)
    base.extend ClassMethods
  end

  module ClassMethods
    def stub_global_object
      ASingleton.any_instance.stubs(:test).returns("stubbed")
    end
  end
end

class TestOne < Test::Unit::TestCase
  def test_real
    # will fail because ASingleton is already stubbed
    assert_equal "real", ASingleton.instance.test
  end
  def test_stub
    ASingleton.any_instance.stubs(:test).returns("stubbed")
    assert_equal "stubbed", ASingleton.instance.test
  end
end

class TestTwo < Test::Unit::TestCase
  include AStubber
  stub_global_object

  def test_real
    assert_equal "real", ASingleton.instance.test
  end
  def test_stub
    ASingleton.any_instance.stubs(:test).returns("stubbed")
    assert_equal "stubbed", ASingleton.instance.test
  end
end
```

**Comment by floehopper** [comment] 2018-03-27 18:40
@lzap Thanks for reporting this and including an example of a failing test. I think this is a duplicate of #292, so I'm going to reference this issue from that one and close this issue. I hope that's OK.

**Closed by floehopper** 2018-03-27 18:40 UTC

**Comment by lzap** [comment] 2018-03-28 11:48
Yeah absolutely I should pay more attention when I was searching, thanks!
