### ISSUE TITLE
Rails 4.2.2 and mocha 1.1.0 not correctly stubbing

### ISSUE THREAD

**Issue by mpasad** [freerange/mocha#233] opened 2015-09-30 11:07 UTC
I am stubbing a method `current_user` in the `ApplicationController` in the `test_helper` class.

snippet of `test_helper.rb`:

```ruby
ENV['RAILS_ENV'] ||= 'test'
require File.expand_path('../../config/environment', __FILE__)
require 'rails/test_help'
require "minitest/reporters"
require "minitest/rails/capybara"
#require "capybara/poltergeist"
require 'mocha/mini_test'

module LoginHelper
  # Simulates a URS login as the specified user.
  def login_as(user, profile = {})
    Rails.cache.write("user_profile_#{user.uid}",
                      "first_name"    => profile["first_name"] || "Example",
                      "last_name"     => profile["last_name"] || "User",
                      "email_address" => profile["email_address"] || "foo@example.com")

    if defined? session
      # Controller test, set the session directly.
      session[:current_user] = user
    else
      # Integration test, mock the current_user method.
      puts "Login as called using user #{user.inspect}"
      ApplicationController.any_instance.stubs(:current_user).returns(user)
    end
  end
end
```

and include this module in 

```ruby
class ActionDispatch::IntegrationTest
  include Capybara::DSL
  include LoginHelper
  
end
```

In the integration test: The current user method does not return the correct value so no user is logged in. 
The `current_user` method is used by a view to display the logged in user. The `current_user` is returning:

`#{current_user.inspect} => {:uid=>nil, :is_admin=>false}`  instead of returning:

`#<User id: 135138680, uid: "admin", is_admin: true, created_at: "2015-09-30 10:45:59", updated_at: "2015-09-30 10:45:59">`

```ruby
require 'test_helper'

class NotificationsEditTest < ActionDispatch::IntegrationTest

  def setup
  end
  
  def teardown
    Capybara.reset_sessions!
  end

  test "can edit notifications as admin" do
    puts users(:admin).inspect
    login_as (users(:admin))
    visit "/client_applications/#{client_applications(:one).id}"
    assert page.has_content? "ONE"
    puts page.body
  end
  
end
```

**Comment by floehopper** [comment] 2015-10-02 13:45
@mpasad: I hope you don't mind, but I've edited your description of the issue to add syntax-highlighting.

**Comment by mpasad** [comment] 2015-10-02 13:47
That's fine, for now I had to write my tests is rspec instead of minitest,
would really like this fixed.

Maitreyee

**Comment by floehopper** [comment] 2015-10-02 14:32
I've attempted to reproduce the problem you described the `issue-233` branch of this relatively pristine Rails app. It's currently using Rails v4.2.1, not v4.2.2, but I doubt that's causing the problem.

You can see the significant changes in this [comparison page](https://github.com/mocha-rb/mocha-with-rails-4.2.1/compare/issue-233).

Since you haven't included your `Gemfile`, I had to guess that you're using the `minitest-rails-capybara` gem, although I notice your integration test inherits from `ActionDispatch::IntegrationTest` whereas I had to inherit from `Capybara::Rails::TestCase` in order to get access to the Capybara methods, so I may have got that wrong.

As you can see from my [integration test](https://github.com/mocha-rb/mocha-with-rails-4.2.1/compare/issue-233#diff-65192622163ffce0abb9d53572da3fb8), I do **not** see the same problem as you i.e. the stubbing is working as I expect.

If I'm going to make any more progress on this, you're going to need to help me reproduce the problem in a simplified bunch of code like the Rails app mentioned above. Also I will need to see your `Gemfile`, `Gemfile.lock` and know exacty what version of Ruby you are using.

One last thought: What driver are you using with Capybara? If you're using one that runs in a different process (most of them other than the default `Rack::Test` one), then mocking won't work, because the `ApplicationController` class that's actually being used on the "server" will be in a different memory space.

**Comment by mpasad** [comment] 2015-10-02 14:33
I am using poltergeist driver.

**Comment by floehopper** [comment] 2015-10-02 14:42
As I explained at the bottom of my last response. If you're using the poltergeist driver for Capybara then I'm pretty sure your application code is executing in a **different process** than your test code. This means that the `ApplicationController` class you reference in your test is not the one that is being used in the server process and hence any stubs you set up on it will not work in server-side code.

In general it's not a great idea to stub things in integration/acceptance tests since it's supposed to be a more realistic scenario. I'd suggest you use calls to Capybara methods to actually login to your app through the user interface and then group these calls into a helper method which you can re-use across your integration tests. I hope that makes sense. I'm going to close this issue, since Mocha is working as expected.

**Closed by floehopper** 2015-10-02 14:42 UTC
